const gulp = require('gulp');
const watch = require('gulp-watch');

const browserify = require('browserify');
const compass = require('gulp-compass');
const pug = require('gulp-pug');
const sass = require('gulp-sass');
const streamify = require('gulp-streamify');
const concat = require('gulp-concat');
const minify = require('gulp-minify-css');
const plumber = require('gulp-plumber');
const rename = require('gulp-rename');
const source = require('vinyl-source-stream');
const uglify = require('gulp-uglify');
const argv = require('yargs').argv;
const spawn = require('child_process').spawn;
const path = require('path');
const _ = require('lodash');
const cleanCSS = require('gulp-clean-css');
const gzip = require('gulp-gzip');
const watchify = require('gulp-watchify');

const rootPath = path.join(__dirname, './');

const sassWatch = path.join(rootPath, 'src/sass/**/*.sass');
const pugWatch = path.join(rootPath, 'src/pug/**/*.pug');
const jsWatch = path.join(rootPath, 'src/js/**/*.js');

const jsOuted = path.join(rootPath, 'public/js/**/*.js');
const cssOuted = path.join(rootPath, 'public/css/**/*.css');

const jsOut = path.join(rootPath, 'public/js');
const cssOut = path.join(rootPath, 'public/css/');
const pugOut = path.join(rootPath, 'public/');


// 実際に使うコマンド

//// コンパイル
gulp.task('watch', ['enable-watch-mode', 'js', 'sass', 'pug']);
//// ライブラリパッキング（ライセンス表記）
gulp.task('vendor', ['vendor-packing']);
//// gzipあり圧縮
gulp.task('hard', ['hard-packing']);
//// gzipなし圧縮
gulp.task('soft', ['soft-packing']);


// task

const onError = (err) => {
  console.log(err.toString());
  this.emit('end');
};

// gulpfile自体の更新時にgulpを再起動する
gulp.task('default', function () {
  let p = undefined;

  let spawnChildren = (e) => {
    p && p.kill();
    p = spawn('gulp', ['watch'], {stdio: 'inherit'});
  };

  gulp.watch('gulpfile.js', spawnChildren);
  spawnChildren(null);
});

// ライセンスを残したままでbrowserifyをかける
// 巨大ライブラリを別ファイルとしてコンパイルしておきたい時に使う

gulp.task('vendor-packing', () => {
  browserify({
    entries: ['./vendor.js'],
    debug: true
  })
    .plugin('licensify')
    .bundle()
    .on('error', onError)
    .pipe(source('built.js'))
    .pipe(streamify(uglify({output: {comments: /generated by licensify/}})))
    .pipe(rename('vendor.min.js'))
    .pipe(gulp.dest(jsOut));
});

// JavaScript ES2015

let watching = false;
gulp.task('enable-watch-mode', () => watching = true);
gulp.task('js', watchify((watchify) => {
  gulp
    .src(jsWatch)
    .pipe(watch(jsWatch))
    .pipe(watchify({
      watch: watching,
      transform: ['babelify']
    }))
    .pipe(gulp.dest(jsOut));
}));

// Sass

gulp.task('sass', (e) => {
  gulp
    .src(sassWatch)
    .pipe(watch(sassWatch))
    .pipe(plumber())
    .pipe(sass({minifier: false}))
    .pipe(gulp.dest(cssOut));
});

// Pug

gulp.task('pug', () => {
  gulp
    .src(pugWatch)
    .pipe(watch(pugWatch))
    .pipe(plumber())
    .pipe(pug())
    .pipe(gulp.dest(pugOut));
});

// gzipあり圧縮

gulp.task('hard-packing', () => {
  gulp
    .src(jsOuted)
    .pipe(streamify(uglify()))
    .pipe(gzip())
    .pipe(gulp.dest(jsOut));

  gulp
    .src(cssOuted)
    .pipe(cleanCSS())
    .pipe(gzip())
    .pipe(gulp.dest(cssOut));
});

// gzip無し圧縮

gulp.task('soft-packing', () => {
  gulp
    .src(jsOuted)
    .pipe(streamify(uglify()))
    .pipe(gulp.dest(jsOut));

  gulp
    .src(cssOuted)
    .pipe(cleanCSS())
    .pipe(gulp.dest(cssOut));
});
